# Game
GAME_MAX_FPS = 60

# Directions
DIRECTION_NONE = 0
DIRECTION_UP = 1
DIRECTION_RIGHT = 2
DIRECTION_DOWN = 3
DIRECTION_LEFT = 4

# Board
BOARD_WIDTH = 50
BOARD_HEIGHT = 50
BOARD_PLAYER_SPAWN_SIZE = 5
BOARD_TILE_NEUTRAL_COLOR = (77, 77, 77)

# Window
WINDOW_WIDTH = 800
WINDOW_HEIGHT = 800

# Player
PLAYER_DELTA_MOVEMENT = 0.125  # It must be: "< 1","finite binary expansion", # "x * PLAYER_DELTA_MOVEMENT = 1 (x > 1)"


